# Generated by Django 2.2.28 on 2023-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("published", models.DateTimeField()),
                ("title", models.TextField()),
                ("subtitle", models.TextField(null=True)),
                ("teaser", models.TextField()),
                ("body", models.TextField()),
                ("link", models.URLField(null=True)),
                ("image", models.URLField(null=True)),
            ],
            options={
                "ordering": ("created",),
            },
        ),
    ]
