# Generated by Django 2.2.28 on 2023-11-24 15:06

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_auto_20231013_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="flags",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="original",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
