# Generated by Django 4.2.28 on 2026-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_consumer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="original",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
